# docker-compose.override.yml - Development Overrides
version: '3.8'

services:
  backend:
    environment:
      - DEBUG_MODE=true
      - VERBOSE_LOGGING=true
      - LOG_LEVEL=debug
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    environment:
      - FAST_REFRESH=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mongodb:
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

---
